<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "{{%user}}".
 *
 * @property integer $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 */
class User extends \common\models\User
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    public static function getStatusOptions(){
        return [
            self::STATUS_ACTIVE => '正常',
            self::STATUS_DELETED => '删除',
        ];
    }

    public function load($data, $formName = null)
    {
        if(parent::load($data, $formName)){
            $password = $this->getAttribute('password_hash');
            $this->setPassword($password);
            $this->generateAuthKey();
            $this->generatePasswordResetToken();
            return true;
        }
        return false;
    }

//    public function attributes()
//    {
//        $result = parent::attributes(); // TODO: Change the autogenerated stub
//        $result['created_at'] = 'created_at:';
//        $result['updated_at'] = '';
//        return $result;
//    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username',  'password_hash', 'email'], 'required'],
            [['status'], 'integer'],
            [['username', 'password_hash', 'password_reset_token', 'email'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => '用户名',
            'auth_key' => 'Auth Key',
            'password_hash' => '密码',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @inheritdoc
     * @return UserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserQuery(get_called_class());
    }
}
